export const REHYDRATE_STATE = 'REHYDRATE_STATE'
export const ADD_PRIVATE_KEY = 'ADD_PRIVATE_KEY'
export const SET_PRIVATE_KEYS = 'SET_PRIVATE_KEYS'
export const ADD_PUBLIC_KEY = 'ADD_PUBLIC_KEY'
export const SET_PUBLIC_KEYS = 'SET_PUBLIC_KEYS'

export const SUBSCRIBED_ACTIONS = [
  ADD_PRIVATE_KEY,
  ADD_PUBLIC_KEY,
  SET_PUBLIC_KEYS,
  SET_PRIVATE_KEYS
]